name: Build and Release Vulnerawise

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for multiple platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GitHub
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull code from private repository
        run: |
          git clone git@github.com:your-username/private-repo.git
          cd private-repo
          # Add any additional commands to prepare the code

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Adjust if needed

      - name: Build binary
        run: |
          mkdir -p bin
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o bin/vulnerawise-${{ matrix.goos }}-${{ matrix.goarch }} ./main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vulnerawise-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/vulnerawise-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin

      - name: Rename artifacts for release
        run: |
          mkdir release
          for file in bin/*/*; do
            filename=$(basename $file)
            if [[ $filename == *windows* ]]; then
              # Add .exe extension to Windows builds if not already there
              if [[ $filename != *.exe ]]; then
                mv "$file" "release/${filename}.exe"
              else
                mv "$file" "release/${filename}"
              fi
            else
              # Non-Windows builds
              mv "$file" "release/${filename}"
            fi
          done

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1
          name: "Vulnerawise v0.1"
          body: "Initial release of Vulnerawise."
          draft: false
          prerelease: false
          files: release/*
